firstproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from . import views
from django.conf.urls import url

app_name = 'music'

urlpatterns =[
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', views.check, name='detail'),
   # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    url(r'song/add/$', views.SongCreate.as_view(), name='song-add'),

    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    url(r'^check/', views.check),
    url(r'^(?P<pk>[0-9]+)/$/', views.check)
]

music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=250)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.album_id})

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from .models import Album, Song
from django.shortcuts import get_object_or_404, get_list_or_404
from django.shortcuts import render, redirect
from urllib import request
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponse


def check(request, pk):
    print("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWw")
    print(pk)
    print("QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQq")
    album = Album.objects.filter(id= pk).first()
    songs = Song.objects.filter(album_id=pk).all()
    print("VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV")
    return render(request, 'music/album_detail.html', {'songs': songs, 'album': album})

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    print('***************************************88')
    print(Song.objects.raw('select * from music_song'))
    print('***************************************88')
    songs = Song.objects.all()
    # template_name = 'music/detail.html'

    def details(request):
        songs = Song.objects.all()
        print("VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV")
        return render(request, 'music:detail', songs)


#    contact_object_name = 'all_songs'

#    def get_queryset(self):
#        return Song.objects.all()


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongCreate(CreateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'is_favorite']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete?</p>
    <input type="submit" value="Confirm" />
</form>

music/templates/music/album_detail.html
{% extends 'music/base.html' %}
{% block title %}Album details for {{ album.album_title }}{% endblock %}

{% block body %}

    <div class="container">


    <div class="container">
      <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12  toppad" >


          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{ album.album_title }} By {{ album.artist }}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center">
                    <img alt="User Pic" src="/media/{{ album.album_logo }}" class="img-responsive">
                </div>

                <div class=" col-md-9 col-lg-9 ">
                    <table class="table">
    <thead>
      <tr>
        <th>Song Title</th>
        <th>Audio Type</th>
        <th>Favorite</th>
      </tr>

    </thead>
    <tbody>


    {%  for song in songs %}

    <tr>
        <td>{{ song.song_title }}</td>
        <td>{{ song.file_type }}</td>
        <td>{{ song.is_favorite }}</td>
    </tr>

    {%  endfor %}
    </tbody>

  </table>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                    </div>

          </div>
        </div>
      </div>
    </div>

    </div>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Alora{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Alora</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:song-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Song
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}

    <div class="container">


    <div class="container">
      <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12  toppad" >


          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{ album.album_title }} By {{ album.artist }}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center">
                    <img alt="User Pic" src="/media/{{ album.album_logo }}" class="img-responsive">
                </div>

                <div class=" col-md-9 col-lg-9 ">
                    <table class="table">
    <thead>
      <tr>
        <th>Song Title</th>
        <th>Audio Type</th>
        <th>Favorite</th>
      </tr>

    </thead>
    <tbody>
    {%  for song in songs %}
    <tr>
        <p>{{ song.title }}</p>
    </tr>

    {%  endfor %}
    </tbody>
  </table>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                    </div>

          </div>
        </div>
      </div>
    </div>

    </div>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
             <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<div class="container">
    <div id="products" class="row list-group">
     {% for album in all_albums %}
        <div class="item  col-xs-4 col-lg-4">
            <div class="thumbnail">
                <img class="group list-group-image" src="/media/{{ album.album_logo }}" alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        {{ album.album_title }}</h4>
                    <span>By : {{ album.artist }}</span>

                    <div class="row">
                        <br>
                        <div class="col-xs-4 col-md-4">
                            <a class="btn btn-success" href="{% url 'music:detail' album.id %}">View Details</a>
                        </div>
                        <div class="col-xs-2 col-md-2">
                            <a class="btn btn-danger" href="album/{{ album.id }}/delete"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     {% endfor %}

    </div>
</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}